name: default
kind: pipeline
type: kubernetes

trigger:
  branches:
    - master
  event:
    - push

steps:

- name: "deploy demo"
  image: dtzar/helm-kubectl:3.4.0
  volumes:
    - /home/mahdi/.kube/:/mamad/shit/fuck/yea/no/llllll/mmm/kkkk/

       
  commands:
    - export KUBECONFIG=/mamad/shit/fuck/yea/no/llllll/mmm/kkkk/config    #corect
    - echo "deploy demo"
    - kubectl get ns


# https://discourse.drone.io/t/problems-with-secrets/3286    