name: default
kind: pipeline
type: kubernetes

trigger:
  branches:
    - master
  event:
    - push


steps:


  - name: deploy
    image: pelotech/drone-helm3
    settings:
      helm_command: upgrade
      add_repos: "https://kubernetes-charts.storage.googleapis.com"
      chart: stable/docker-registry
      namespace: drone-test
      release: docker-registry
      kube_service_account: drone-ci-ath
      api_server:
        from_secret: prod_api_server
      kubernetes_token:
        from_secret: prod_kubernetes_token
      kube_certificate:
        from_secret: prod_kube_certificate 






# https://discourse.drone.io/t/problems-with-secrets/3286    