name: default
kind: pipeline
type: kubernetes

trigger:
  branches:
    - master
  event:
    - push


steps:

  # - name: "build"
  #   image: docker:stable-dind
  #   volumes:
  #     - name: docker
  #       path: /var/run/
  #   commands:
  #     - docker build -t simpleapp_drone:latest .



  - name: deploy
    image: pelotech/drone-helm3
    settings:
      helm_command: upgrade
      chart: /home/mahdi/manifest/simpleapp_drone/simpleapp
      namespace: drone-test
      release: release
      kube_service_account: drone-ci-ath
      api_server:
        from_secret: prod_api_server
      kubernetes_token:
        from_secret: prod_kubernetes_token
      kube_certificate:
        from_secret: prod_kube_certificate



volumes:
- name: docker
  host:
    path: /var/run/



# https://discourse.drone.io/t/problems-with-secrets/3286    