name: default
kind: pipeline
type: kubernetes

trigger:
  branches:
    - master
  event:
    - push


steps:


  - name: deploy
    image: pelotech/drone-helm3
    settings:
      helm_command: upgrade
      chart: stable/docker-registry
      namespace: drone-test
      release: docker-registry
      api_server:
        from_secret: prod_api_server
      kubernetes_token:
        from_secret: prod_kubernetes_token






# https://discourse.drone.io/t/problems-with-secrets/3286    